version: '1.0.{build}'
image: Visual Studio 2019
configuration: Release
platform:
    - x64
branches:
  only:
    - master

environment:
    qt: 5.14
    msvc: msvc2017
    vs: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build
    QTDIR: C:\Qt\5.14.2\msvc2017_64

    MyProjectDir: C:\projects\InstallationPackage
    
skip_tags: true

before_build: 
    #- set PATH=%PATH%;%QTDIR%\bin;
    #- set vcvarsall=%vs%\vcvarsall.bat
    #- call "%vcvarsall%" x64
    - set PATH=%PATH%;%QTDIR%\bin;
    - call %QTDIR%\bin\qtenv2.bat
    - call %vs%\vcvars64.bat x64
    
build_script:
    #- MSBuild %MyProjectDir%TianLiInstallationPackage\TianLiInstallationPackage.vcxproj
    - cd %MyProjectDir%\TianLiInstallationPackage
    - qmake
    - nmake
    
after_build:
    # copy include and source code files
    #- ls
    - mkdir $env:MyProjectDir\x64\build\
    - ps: cp -r $env:MyProjectDir\x64\Release\TianLi_setup.exe $env:MyProjectDir\x64\build\
    - cd $env:MyProjectDir\x64\build\
    - windeployqt TianLi_setup.exe

    - 7z a TianLi_setup.zip $env:MyProjectDir\x64\build\*
    - echo %APPVEYOR_BUILD_VERSION% >version.tag
    #- appveyor PushArtifact version.tag
    #- appveyor PushArtifact TianLi_setup.7z
    
#artifacts:
    #- path: build/Release
    #artifacts path name must be appveyor API
