version: '1.0.{build}'
image: Visual Studio 2019
configuration: Release
platform:
    - x64
branches:
  only:
    - master

environment:
    qt: 5.14
    msvc: msvc2017
    vs: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
    QTDIR: C:\Qt\5.14.2\msvc2017_64

    MyProjectDir: C:\projects\InstallationPackage\
    
skip_tags: true
  
install:
    - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()
    - dir C:\Qt
    - dir C:\

    # download opencv:
    # - mkdir %OpenCvDir%
    #- dir %OpenCvDir%
    # - appveyor DownloadFile %OpenCvUrl%
    # - 7z x ./*.zip -y -o%OpenCvDir%
    # - rm -f ./*.zip
    #- dir %OpenCvDir%
    #- dir %OpenCvDir%x64\vc15\staticlib
    
before_build: 
    #- dir  %MyProjectDir%
    #- dir  %OpenCvDir%
    set PATH=%PATH%;%QTDIR%\bin;
    set vcvarsall=%vs%\vcvarsall.bat
    call "%vcvarsall%" x64
build_script:
    #- MSBuild %MyProjectDir%TianLiInstallationPackage\TianLiInstallationPackage.vcxproj
    - cd %MyProjectDir%TianLiInstallationPackage
    - qmake
    - make
    
after_build:
    # copy include and source code files
    #- ls
    - mkdir %MyProjectDir%x64\build\
    - ps: cp -r $env:MyProjectDir\TianLiInstallationPackage\x64\Release\*.dll $env:MyProjectDir\x64\build\

    - 7z a cvautotrack.7z %MyProjectDir%x64\build\*
    - echo %APPVEYOR_BUILD_VERSION% >version.tag
    #- appveyor PushArtifact version.tag
    #- appveyor PushArtifact cvAutoTrack.7z
    
#artifacts:
    #- path: build/Release
    #artifacts path name must be appveyor API
